namespace Thuai.GameLogic;

using Thuai.GameLogic.StrategyCards;

/// <summary>
/// Orchestrates a single trading day (one of 3 rounds in a game).
/// Runs for a configurable number of ticks (default 2000) and manages the order book,
/// match engine, NPC traders, news system, research reports, and strategy card effects.
///
/// This class runs on the game tick thread. All player-facing action handlers
/// (HandleLimitBuy, HandleLimitSell, etc.) are called from the GameController
/// when player messages arrive, and must be safe to call between ticks.
/// </summary>
public class TradingDay
{
    private readonly object _lock = new();
    private readonly int _maxTicks;
    private readonly long _initialGoldPrice;
    private readonly Dictionary<string, Player> _players;
    private readonly OrderBook _orderBook;
    private readonly MatchEngine _matchEngine;
    private readonly NewsSystem _newsSystem;
    private readonly NPCTrader _npcTrader;
    private readonly ResearchSystem _researchSystem;

    private int _currentTick;
    private bool _isFinished;
    private readonly Dictionary<int, long> _midPriceHistory = new();

    // Track initial NAV per player for stop-loss blade threshold calculation.
    private readonly Dictionary<string, long> _initialNAV = new();

    // Track which players have active malicious shorting, so the broadcast layer
    // can inject fake sell levels into the opponent's market data view.
    private readonly List<(string OwnerToken, long Price, int Quantity)> _fakeSellLevels = new();

    // Per-tick insider news previews to be consumed by the broadcast layer.
    private readonly List<(string PlayerToken, News Preview)> _pendingInsiderPreviews = new();

    // ---- Events ----

    /// <summary>Fired when a news item is published (real or fake).</summary>
    public event Action<News>? OnNewsPublished;

    /// <summary>Fired after each trade is executed by the match engine.</summary>
    public event Action<Trade>? OnTradeExecuted;

    /// <summary>Fired when a research report is settled (reward/penalty applied).</summary>
    public event Action<ResearchReport>? OnReportSettled;

    /// <summary>Fired when a player's strategy card skill activates. Args: playerToken, skillName.</summary>
    public event Action<string, string>? OnSkillActivated;

    /// <summary>
    /// Fired when an insider player should receive a news preview early.
    /// Args: playerToken, the pre-generated news content.
    /// </summary>
    public event Action<string, News>? OnInsiderNewsPreview;

    // ---- Public read-only state ----

    public int CurrentTick => _currentTick;
    public bool IsFinished => _isFinished;
    public OrderBook OrderBook => _orderBook;
    public MatchEngine MatchEngine => _matchEngine;
    public NewsSystem NewsSystem => _newsSystem;
    public ResearchSystem ResearchSystem => _researchSystem;

    /// <summary>
    /// Fake sell levels generated by malicious shorting this tick.
    /// The broadcast layer should merge these into the opponent's visible asks.
    /// Cleared at the start of each tick.
    /// </summary>
    public IReadOnlyList<(string OwnerToken, long Price, int Quantity)> FakeSellLevels => _fakeSellLevels;

    /// <summary>
    /// Insider news previews generated this tick for players with the InsiderInfo card.
    /// The broadcast layer should send these as early news messages to the specified players.
    /// Cleared at the start of each tick.
    /// </summary>
    public IReadOnlyList<(string PlayerToken, News Preview)> PendingInsiderPreviews => _pendingInsiderPreviews;

    public TradingDay(
        Dictionary<string, Player> players,
        int maxTicks,
        long initialGoldPrice,
        int newsIntervalMin,
        int newsIntervalMax,
        int researchWindow,
        int researchSettlementDelay,
        long baseResearchReward,
        int npcOrdersPerTick)
    {
        _maxTicks = maxTicks;
        _initialGoldPrice = initialGoldPrice;
        _players = players;
        _orderBook = new OrderBook(initialGoldPrice);
        _matchEngine = new MatchEngine(_orderBook, players);
        _newsSystem = new NewsSystem(newsIntervalMin, newsIntervalMax, researchWindow);
        _npcTrader = new NPCTrader(npcOrdersPerTick);
        _researchSystem = new ResearchSystem(_newsSystem, baseResearchReward, researchWindow, researchSettlementDelay);

        _matchEngine.OnTradeExecuted += HandleTradeExecuted;
    }

    /// <summary>
    /// Prepare the trading day: reset player state, seed the order book with NPC liquidity,
    /// and record the initial mid price. Must be called before the first Tick().
    /// </summary>
    public void Initialize()
    {
        _currentTick = 0;
        _isFinished = false;
        _midPriceHistory.Clear();
        _initialNAV.Clear();
        _fakeSellLevels.Clear();
        _pendingInsiderPreviews.Clear();

        // Reset players for the new day.
        foreach (var player in _players.Values)
        {
            player.ResetForNewDay();
            StrategyCardManager.ResetDailyCardState(player);
        }

        // Seed the order book with initial NPC orders to establish a spread.
        // Multiple rounds give the book a realistic shape before player trading begins.
        for (int i = 0; i < 10; i++)
        {
            _npcTrader.GenerateOrders(_matchEngine, _orderBook, null, 0);
        }
        _matchEngine.ProcessTick(0);

        RecordMidPrice(0);

        // Snapshot initial NAV after the book is seeded so the mid price is meaningful.
        long midPrice = _orderBook.MidPrice;
        foreach (var player in _players.Values)
        {
            _initialNAV[player.Token] = player.CalculateNAV(midPrice);
        }
    }

    // =========================================================================
    //  Main tick — called by GameController once per game tick
    // =========================================================================

    /// <summary>
    /// Advance the trading day by one tick. Orchestrates all subsystems in order:
    /// per-tick resets, card ticks, circuit breaker check, malicious shorting,
    /// stop-loss checks, NPC orders, matching, mid-price recording, news, and
    /// research settlement.
    /// </summary>
    public void Tick()
    {
        lock (_lock)
        {
        _currentTick++;

        if (_currentTick > _maxTicks)
        {
            _isFinished = true;
            return;
        }

        // 1. Reset per-tick counters, unlock matured locked gold, and clear per-tick buffers.
        _pendingInsiderPreviews.Clear();
        foreach (var player in _players.Values)
        {
            player.ResetTickCounters();
            player.UpdateLockedGold(_currentTick);
        }

        // 2. Tick strategy cards (cooldown decrements, timed effect expiry).
        foreach (var player in _players.Values)
        {
            StrategyCardManager.TickCards(player, _currentTick);
        }

        // 3. Check circuit breaker (拔网线).
        bool circuitBreakerActive = IsCircuitBreakerActive();

        // 4. Generate fake sell levels for malicious shorting (恶意做空).
        //    These are not real orders; they are injected into broadcast data only.
        RefreshFakeSellLevels();

        // 5. Check stop-loss blade (止损名刀) triggers.
        CheckStopLoss();

        // 6. Generate NPC orders — skipped during circuit breaker.
        if (!circuitBreakerActive)
        {
            _npcTrader.GenerateOrders(_matchEngine, _orderBook, _newsSystem.CurrentSentiment, _currentTick);
        }

        // 7. Process matching engine (move delayed orders into book + match).
        _matchEngine.ProcessTick(_currentTick);

        // 8. Record mid price for research settlement lookups.
        RecordMidPrice(_currentTick);

        // 8.5 Insider news preview: if 3 ticks before the next news, pre-generate and
        //     send to players holding the InsiderInfo card.
        CheckInsiderNewsPreview();

        // 9. Tick news system — may publish a new news item.
        var news = _newsSystem.Tick(_currentTick);
        if (news != null)
        {
            OnNewsPublished?.Invoke(news);
        }

        // 10. Settle research reports whose settlement window has elapsed.
        SettlePendingReports();

        // 11. Check if the day is done.
        if (_currentTick >= _maxTicks)
        {
            _isFinished = true;
        }
        } // end lock
    }

    // =========================================================================
    //  Player action handlers — called by GameController on message receipt
    // =========================================================================

    /// <summary>
    /// Submit a limit buy order for the player.
    /// Returns true if the order was accepted, false otherwise.
    /// </summary>
    public bool HandleLimitBuy(string playerToken, long price, int quantity)
    {
        lock (_lock)
        {
        if (_isFinished) return false;
        if (IsCircuitBreakerActive()) return false;
        if (!_players.TryGetValue(playerToken, out var player)) return false;

        bool isIceberg = player.ActiveCards.Any(c => c is IcebergOrder);
        var order = _matchEngine.SubmitOrder(playerToken, OrderSide.Buy, price, quantity, _currentTick, isIceberg);
        return order != null;
        }
    }

    public bool HandleLimitSell(string playerToken, long price, int quantity)
    {
        lock (_lock)
        {
        if (_isFinished) return false;
        if (IsCircuitBreakerActive()) return false;
        if (!_players.TryGetValue(playerToken, out var player)) return false;

        bool isIceberg = player.ActiveCards.Any(c => c is IcebergOrder);
        var order = _matchEngine.SubmitOrder(playerToken, OrderSide.Sell, price, quantity, _currentTick, isIceberg);
        return order != null;
        }
    }

    public bool HandleCancelOrder(string playerToken, long orderId)
    {
        lock (_lock)
        {
        if (_isFinished) return false;
        return _matchEngine.CancelOrder(playerToken, orderId);
        }
    }

    public bool HandleSubmitReport(string playerToken, int newsId, Prediction prediction)
    {
        lock (_lock)
        {
        if (_isFinished) return false;
        if (!_players.TryGetValue(playerToken, out var player)) return false;
        if (!player.CanSubmitReport()) return false;

        // Check for quant cluster extended research window and decay multiplier.
        int? extendedWindow = null;
        double decayMultiplier = 1.0;
        var quantCard = player.ActiveCards.FirstOrDefault(c => c is QuantCluster) as QuantCluster;
        if (quantCard != null)
        {
            extendedWindow = quantCard.ExtendedResearchWindow;
            decayMultiplier = quantCard.DecayMultiplier;
        }

        var report = _researchSystem.SubmitReport(playerToken, newsId, prediction, _currentTick, extendedWindow, decayMultiplier);
        if (report != null)
        {
            player.ReportsSentThisTick++;
            return true;
        }
        return false;
        }
    }

    public bool HandleActivateSkill(string playerToken, string skillName, string? direction = null)
    {
        lock (_lock)
        {
        if (_isFinished) return false;
        if (!_players.TryGetValue(playerToken, out var player)) return false;

        var card = StrategyCardManager.FindActiveCard(player, skillName);
        if (card == null) return false;

        // StrategyCard.CanActivate() checks IsPassive and cooldown.
        if (card is StrategyCard sc && !sc.CanActivate()) return false;

        return card switch
        {
            FlashTrading ft => ActivateFlashTrading(player, ft),
            TargetedPurchase tp => ActivateTargetedPurchase(player, tp),
            MaliciousShorting ms => ActivateMaliciousShorting(player, ms),
            NetworkDisconnect nd => ActivateNetworkDisconnect(player, nd),
            DarkPoolTrading dp => direction?.ToLowerInvariant() == "sell"
                ? ActivateDarkPoolSell(player, dp)
                : ActivateDarkPoolBuy(player, dp),
            SentimentManipulation sm => ActivateSentimentManipulation(player, sm),
            _ => ActivateGeneric(player, card)
        };
        } // end lock
    }

    // =========================================================================
    //  Settlement / query methods
    // =========================================================================

    /// <summary>
    /// Calculate each player's net asset value at the current mid price.
    /// Called at end of day for settlement and ranking.
    /// </summary>
    public Dictionary<string, long> CalculateSettlement()
    {
        long midPrice = _orderBook.MidPrice;
        var navs = new Dictionary<string, long>();
        foreach (var player in _players.Values)
        {
            navs[player.Token] = player.CalculateNAV(midPrice);
        }
        return navs;
    }

    /// <summary>Get all pending orders for a player (for status display).</summary>
    public List<Order> GetPlayerPendingOrders(string playerToken)
    {
        return _orderBook.GetPlayerOrders(playerToken);
    }

    /// <summary>Get total trade count for a player (used for tiebreaker scoring).</summary>
    public int GetPlayerTradeCount(string playerToken)
    {
        if (_players.TryGetValue(playerToken, out var player))
            return player.TotalTradeCount;
        return 0;
    }

    /// <summary>
    /// Look up the recorded mid price for a given tick.
    /// Falls back to the nearest recorded tick if the exact tick is missing,
    /// or to the initial gold price if no history exists.
    /// </summary>
    public long GetMidPriceAtTick(int tick)
    {
        if (_midPriceHistory.TryGetValue(tick, out long price))
            return price;

        if (_midPriceHistory.Count == 0)
            return _initialGoldPrice;

        // Find the nearest recorded tick.
        int bestKey = 0;
        int bestDist = int.MaxValue;
        foreach (var key in _midPriceHistory.Keys)
        {
            int dist = Math.Abs(key - tick);
            if (dist < bestDist)
            {
                bestDist = dist;
                bestKey = key;
            }
        }
        return _midPriceHistory[bestKey];
    }

    // =========================================================================
    //  Private helpers
    // =========================================================================

    /// <summary>
    /// If the current tick is exactly 3 ticks before the next news publish tick,
    /// pre-generate the upcoming news and send a preview to any player holding
    /// the InsiderInfo card. Previews are stored in <see cref="_pendingInsiderPreviews"/>
    /// for the broadcast layer to consume.
    /// </summary>
    private void CheckInsiderNewsPreview()
    {
        const int EarlyTicks = 3;

        if (_currentTick != _newsSystem.NextNewsTick - EarlyTicks)
            return;

        // Collect players with InsiderInfo before doing any generation work.
        var insiderPlayers = new List<Player>();
        foreach (var player in _players.Values)
        {
            if (player.ActiveCards.Any(c => c is InsiderInfo))
                insiderPlayers.Add(player);
        }

        if (insiderPlayers.Count == 0)
            return;

        var previewNews = _newsSystem.PreGenerateNextNews();
        if (previewNews == null)
            return;

        foreach (var player in insiderPlayers)
        {
            _pendingInsiderPreviews.Add((player.Token, previewNews));
            OnInsiderNewsPreview?.Invoke(player.Token, previewNews);
        }
    }

    private void HandleTradeExecuted(Trade trade)
    {
        OnTradeExecuted?.Invoke(trade);
    }

    /// <summary>
    /// Returns true if any player's NetworkDisconnect card currently imposes a
    /// circuit breaker on the exchange.
    /// </summary>
    private bool IsCircuitBreakerActive()
    {
        foreach (var player in _players.Values)
        {
            foreach (var card in player.ActiveCards)
            {
                if (card is NetworkDisconnect nd && nd.IsCircuitBreakerActive(_currentTick))
                    return true;
            }
        }
        return false;
    }

    /// <summary>
    /// Rebuild the fake sell levels list for broadcast.
    /// Malicious shorting generates phantom sell orders near the spread that the
    /// opponent sees but which never enter the real order book.
    /// </summary>
    private void RefreshFakeSellLevels()
    {
        _fakeSellLevels.Clear();

        foreach (var player in _players.Values)
        {
            foreach (var card in player.ActiveCards)
            {
                if (card is MaliciousShorting ms && ms.IsEffectActive(_currentTick))
                {
                    long midPrice = _orderBook.MidPrice;
                    if (midPrice <= 0) continue;

                    // Generate several fake sell levels just below mid price to spook the opponent.
                    for (int i = 0; i < 5; i++)
                    {
                        long fakePrice = midPrice - (i + 1);
                        if (fakePrice <= 0) fakePrice = 1;
                        // Quantity varies between 10 and 50 to look realistic.
                        int fakeQty = 10 + (i * 10);
                        _fakeSellLevels.Add((player.Token, fakePrice, fakeQty));
                    }
                }
            }
        }
    }

    /// <summary>
    /// Check whether any player's StopLossBlade should trigger.
    /// If it does: cancel all their pending orders, activate immunity.
    /// </summary>
    private void CheckStopLoss()
    {
        long midPrice = _orderBook.MidPrice;

        foreach (var player in _players.Values)
        {
            foreach (var card in player.ActiveCards)
            {
                if (card is not StopLossBlade slb) continue;

                long currentNAV = player.CalculateNAV(midPrice);
                long initialNAV = _initialNAV.GetValueOrDefault(player.Token, 0);

                if (!slb.ShouldTrigger(currentNAV, initialNAV)) continue;

                // Cancel all of this player's pending orders.
                var orders = _orderBook.GetPlayerOrders(player.Token);
                foreach (var order in orders)
                {
                    _matchEngine.CancelOrder(player.Token, order.OrderId);
                }

                slb.Trigger(player, _currentTick);
                OnSkillActivated?.Invoke(player.Token, slb.Name);
            }
        }
    }

    /// <summary>
    /// Settle any research reports whose settlement window has elapsed,
    /// and apply the reward or penalty to each player's Mora balance.
    /// </summary>
    private void SettlePendingReports()
    {
        var settledReports = _researchSystem.SettleReports(_currentTick, GetMidPriceAtTick);

        foreach (var report in settledReports)
        {
            if (!_players.TryGetValue(report.PlayerToken, out var player))
                continue;

            if (report.Reward > 0)
            {
                player.AddMora(report.Reward);
            }
            else if (report.Reward < 0)
            {
                // Deduct penalty, but do not let Mora go below zero.
                long penalty = Math.Abs(report.Reward);
                long deduction = Math.Min(penalty, player.Mora);
                player.AddMora(-deduction);
            }

            OnReportSettled?.Invoke(report);
        }
    }

    private void RecordMidPrice(int tick)
    {
        _midPriceHistory[tick] = _orderBook.MidPrice;
    }

    // ---- Skill activation helpers ----

    private bool ActivateFlashTrading(Player player, FlashTrading ft)
    {
        ft.OnActivate(player, _currentTick);
        OnSkillActivated?.Invoke(player.Token, ft.Name);
        return true;
    }

    private bool ActivateTargetedPurchase(Player player, TargetedPurchase tp)
    {
        // Buy PurchaseQuantity gold at DiscountRate below the best bid.
        var bestBid = _orderBook.BestBid;
        if (!bestBid.HasValue) return false;

        long discountPrice = (long)(bestBid.Value * (1.0 - tp.DiscountRate));
        if (discountPrice <= 0) discountPrice = 1;

        long cost = discountPrice * tp.PurchaseQuantity;
        if (player.Mora < cost) return false;

        player.AddMora(-cost);
        player.AddLockedGold(tp.PurchaseQuantity, _currentTick + tp.LockDuration);
        tp.OnActivate(player, _currentTick);
        OnSkillActivated?.Invoke(player.Token, tp.Name);
        return true;
    }

    private bool ActivateMaliciousShorting(Player player, MaliciousShorting ms)
    {
        ms.OnActivate(player, _currentTick);
        OnSkillActivated?.Invoke(player.Token, ms.Name);
        return true;
    }

    private bool ActivateNetworkDisconnect(Player player, NetworkDisconnect nd)
    {
        nd.OnActivate(player, _currentTick);
        OnSkillActivated?.Invoke(player.Token, nd.Name);
        return true;
    }

    /// <summary>
    /// Dark pool buy: purchase TradeQuantity units at mid price from the system,
    /// bypassing the order book entirely (no price impact).
    /// </summary>
    private bool ActivateDarkPoolBuy(Player player, DarkPoolTrading dp)
    {
        long midPrice = _orderBook.MidPrice;
        if (midPrice <= 0) return false;

        long cost = midPrice * dp.TradeQuantity;
        if (player.Mora < cost) return false;

        player.AddMora(-cost);
        player.AddGold(dp.TradeQuantity);
        dp.OnActivate(player, _currentTick);
        OnSkillActivated?.Invoke(player.Token, dp.Name);
        return true;
    }

    /// <summary>
    /// Dark pool sell: sell TradeQuantity units at mid price to the system,
    /// bypassing the order book entirely (no price impact).
    /// </summary>
    private bool ActivateDarkPoolSell(Player player, DarkPoolTrading dp)
    {
        long midPrice = _orderBook.MidPrice;
        if (midPrice <= 0) return false;
        if (player.Gold < dp.TradeQuantity) return false;

        player.AddGold(-dp.TradeQuantity);
        player.AddMora(midPrice * dp.TradeQuantity);
        dp.OnActivate(player, _currentTick);
        OnSkillActivated?.Invoke(player.Token, dp.Name);
        return true;
    }

    private bool ActivateSentimentManipulation(Player player, SentimentManipulation sm)
    {
        // Pick a random sentiment for the fake news.
        var sentiment = Random.Shared.Next(2) == 0
            ? NewsSentiment.Bullish
            : NewsSentiment.Bearish;

        var fakeNews = _newsSystem.InjectFakeNews(_currentTick, player.Token, sentiment);
        sm.OnActivate(player, _currentTick);
        OnNewsPublished?.Invoke(fakeNews);
        OnSkillActivated?.Invoke(player.Token, sm.Name);
        return true;
    }

    private bool ActivateGeneric(Player player, IStrategyCard card)
    {
        card.OnActivate(player, _currentTick);
        OnSkillActivated?.Invoke(player.Token, card.Name);
        return true;
    }
}
